name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  DeterminateCI:
    uses: dataheld/ci/.github/workflows/workflow.yml@pass-thru-failearly
    permissions:
      id-token: "write"
      contents: "read"
    with:
      fail-fast: false
  flake-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@v9
